### ISSUE TITLE
Running with pytest ValueError

### ISSUE THREAD

**Issue by petroslamb** [eventbrite/nose-knows#4]
Hi, trying to use the `py.test` plugin according to the instructions, I get:

```
INTERNALERROR>   
File "pytest_plugin.py", line 66, in parse_test_name begin = item_cls.index("'") + 1 
ValueError: substring not found
```

After an inspection it seems that `item.cls` is `None` , while `item` is a `Function` object of a valid test.

If its just me I guess its my poor debugging, otherwise any help is most welcomed.

`pytest==2.7.3`
`nose-knows==0.1.2`
`capurelog` and `cov` plugins installed

**Comment by eyalr** [comment]
Is this for when you're creating the .knows file or when you're trying to run the tests for a specific file? Please provide the command you're running, as it will help me in debugging.

Thanks!

**Comment by waqashamid** [comment]
Hi, 
I am using the nose-knows plugin. I was trying to generate the .knows file but I am getting " INTERNAL ERROR of ValueError:substring not found. " I have attached the error I am experiencing in the attachment. 
Hoping to hear from you soon. 
[error_log.txt](https://github.com/eventbrite/nose-knows/files/957682/error_log.txt)

**Comment by ebmshenfield** [comment]
@beginner007 Thanks for the detailed output!

The root cause is that the py.test plugin assumes each test item is class based.  It ends up choking on function-based tests because the [pytest.Item `cls` attribute is `None`](https://github.com/eventbrite/nose-knows/blob/3ac3cfc81c7d3bc7beaf2b533ab37a0bbf132779/src/knows/pytest_plugin.py#L65).
